# Generated by Django 3.1.5 on 2021-01-12 23:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_skill', models.CharField(max_length=200)),
                ('languages', models.CharField(max_length=200)),
                ('frameworks', models.CharField(max_length=200)),
                ('technologies', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=400)),
                ('summary', models.TextField()),
                ('text', models.TextField()),
                ('tag', models.TextField(max_length=50)),
                ('type', models.TextField(max_length=50)),
                ('lang', models.CharField(max_length=2)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2021, 1, 12, 23, 10, 50, 60283, tzinfo=utc))),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
