# Generated by Django 3.1.5 on 2021-01-13 03:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Now',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('now', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='About',
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 13, 3, 21, 52, 244337, tzinfo=utc)),
        ),
    ]
